name: 'jaffle_shop'
profile: 'jaffle_shop'

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  +jaffle_shop: 
    

models:
  jaffle_shop:  
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table