name: workflow_dbt-build

# Executa diariamente as 5 da manhã
on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 5 * * *'        

env:    
    DBT_PROFILES_DIR: /home/runner/.dbt 
    PYTHON_VERSION: '3.10'

jobs:
    #Job 1: Build 
    build:
        runs-on: ubuntu-latest
     
        steps:
        - name: Checkout app code
          uses: actions/checkout@v4   # Baixa o código do repositório
     
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Install dbt
          run: pip install dbt-databricks    

        - name: Login to DataBricks and file  
          env:
            DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
            DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
            DATABRICKS_CATALOG: ${{ secrets.DATABRICKS_CATALOG }}
            DATABRICKS_SCHEMA: ${{ secrets.DATABRICKS_SCHEMA }}
          run: |
            # Cria arquivo profiles.yml com o conteúdo entre EOF e EOF
            mkdir -p ${{ env.DBT_PROFILES_DIR }}
            cat > ${{ env.DBT_PROFILES_DIR }}/profiles.yml << EOF
            jaffle_shop:
                target: dev
                outputs:
                dev:
                    type: databricks
                    host: ${{ env.DATABRICKS_HOST }}
                    http_path: ${{ env.DATABRICKS_HTTP_PATH }}
                    token: ${{ env.DATABRICKS_TOKEN }}
                    catalog: ${{ env.DATABRICKS_CATALOG }}
                    schema: ${{ env.DATABRICKS_SCHEMA }}
                    threads: 4
            EOF   

            echo "Arquivo profiles.yml criado em: ${{ env.DBT_PROFILES_DIR }}"
            
        - name: Run dbt deps
          run: dbt deps    

        - name: Run dbt build
          run: dbt build    